### ISSUE TITLE
compose not working in assemble 0.4.17

### ISSUE THREAD

**Issue by akileez** [helpers/handlebars-helper-compose#1]
I recently updated assemble from 0.4.13 to 0.4.17 and realized that compose stopped working. Actually it is working but is not rendering the `{{{content}}}` section for some reason. No errors are being throw off. If more info is needed, please advise.

After a little more checking, the helper `{{post}}` is working fine which is pretty similar to compose. I am assuming `{{compose}}` needs refactoring to adjust for the changes in assemble 0.4.17 for making helpers act like plugins? I tried hacking compose to get it working but to no avail. My javascript skills are lacking. This isn't critical so no rush. Thanks.

**Comment by jonschlinkert** [comment]
thanks for reporting, we'll look into this. I'm pretty sure it's related to the version of handlebars, which we're also looking into.

**Comment by akileez** [comment]
On my way out the door. but found fix...

``` js
}).sort(compare_fn).map(function (obj) {
      // promote id into context
      obj.context.id = obj.id;
      var template2 = Handlebars.compile(options.fn(obj.context));
      var template = Handlebars.compile(obj.content);
      return new Handlebars.SafeString(template2(obj.context) + template(obj.context));
    }).join(options.sep);
```

needed to add additional compile for content then add both to SafeString. Wont be back for a couple of hours. Sorry for the crude response. 

Not really fixed.. data for template2 displays but does not encapsulate data for template. Again, my javascript skills are limited so maybe you can go further. Now I am out the door.

**Comment by akileez** [comment]
I have exhausted myself trying to get compose to work "properly". Must be a change unbeknownst to me. The `{{content}}` block is not being encapsulated within `{{compose}}` during template generation:  `options.fn(obj.context)`. The prior solution (appending content) will work in all cases where `{{content}}` is the last item within the  `{{compose}}` block, otherwise poorly generated html code results.

``` js
// working but not like before.
var template = Handlebars.compile(options.fn(obj.context));
return new Handlebars.SafeString(template(obj.context));

```

``` js
// Doing this makes compose work exactly like aggregate.
var template = Handlebars.compile(obj.content);
return new Handlebars.SafeString(template(obj.context));

```

**Comment by akileez** [comment]
Finally figured the problem: LAYOUTS. 
The new layout helpers use the block helper `{{content}}` and so does `{{compose}}`. After doing some testing of layouts today it hit me. 

Change this ...

``` js
context: processContext(grunt, _.defaults({content: content}, context)),
content: content
...
var template = Handlebars.compile(options.fn(obj.context) + obj.content);
```

to this ...

``` js
context: processContext(grunt, _.defaults({someOtherName: content}, context)),
someOtherName: content
...
var template = Handlebars.compile(options.fn(obj.context));
```

Then use `someOtherName` as the handlebars variable in said partial and we are back in business...
Still learning git so no pull request from me...

**Comment by jonschlinkert** [comment]
I made some massive changes to the helper, please see https://github.com/helpers/handlebars-helper-compose/issues/7

**Comment by jonschlinkert** [comment]
Sorry it took so long to address. with the changes I made you can now do `{{@content}}`.

**Comment by jonschlinkert** [comment]
I'm going to close, please reopen if you think this is still an issue

**Comment by akileez** [comment]
no issues. working fine. thanks a million.
