### ISSUE TITLE
Limit in {{#compose}}

### ISSUE THREAD

**Issue by diogomoretti** [helpers/handlebars-helper-compose#10]
Hello!

How to make a limit in `{{#compose}}`?

```
{{#compose src="posts/*.md"}}
  <h1>Title: {{@title}}</h1>
  {{{@content}}}</p>
{{/compose}}
```

For example: i need the last 3 blog posts.

**Comment by jonschlinkert** [comment]
I just added this option, does this work for you? https://github.com/helpers/handlebars-helper-compose#filtering

Also, here is the filter function as a helper in case you need it for something else (but it won't work for this use case):

``` js
// node_modules
var _ = require('lodash');

module.exports.register = function (Handlebars, options, params) {
  'use strict';
  var opts = options || {};

  Handlebars.registerHelper('last',function(context, num) {
    var result = context.slice(Math.max(context.length - num, 0))
    return new Handlebars.SafeString(result);
  });
};
```

It's used like: 

``` html
{{last foo 3}}
// => returns the last three items in the array
```

**Comment by jonschlinkert** [comment]
Btw, you could probably just use the `compare` option, but that would filter out files after they have been processed. I think this should be faster since it will reduce the number of files that get processed.

**Comment by jonschlinkert** [comment]
@diogomoretti I'm going to go ahead and close. if the solutions I posted don't work for you feel free to re-open

**Comment by diogomoretti** [comment]
Ow. Its work. Sorry for the no response.

**Comment by jonschlinkert** [comment]
:+1:  no prob!

**Comment by diogomoretti** [comment]
I still need to use the "limit" in compose. which syntax I use?

**Comment by jonschlinkert** [comment]
You'll have to try out the solutions I posed and see which one works for you.

**Comment by diogomoretti** [comment]
How to use filter?

**Comment by diogomoretti** [comment]
my compose:

```
{{#compose src="posts/**/*.md"}}
  <h1><a href="{{formatDate date "%Y"}}/{{@basename}}">{{@title}}</a></h1>
  <p>{{{@content}}}</p>
{{/compose}}
```

Gruntfile.js

``` js
pages: {
    options: {
        flatten: true,
        layout: '<%= config.src %>/templates/layouts/default.hbs',
        compose: {
            cwd: 'src/content/blog',
            sortBy: 'date',
            sortOrder: 'desc',
            filter: function(arr) {
                return arr.slice(Math.max(arr.length - 2, 0));
            }
        },
        permalinks: {
            preset: 'pretty'
        }
    },
    files: {
        '<%= config.dist %>/': ['<%= config.src %>/templates/pages/*.hbs']
    }
},
```

But list all 4 blog posts. After resolve this, i need apply the pagination.
