### ISSUE TITLE
Error loading helpers from file: node_modules/handlebars-helper-compose/index.js

### ISSUE THREAD

**Issue by diogomoretti** [helpers/handlebars-helper-compose#12]
When run `grunt server`, show me the error:

```
Running "assemble:pages" (assemble) task
Error loading helpers from file: node_modules/handlebars-helper-compose/index.js
TypeError: Cannot read property 'languages' of undefined
Assembling dist/blog.html OK
Assembling dist/index.html ERROR
Warning: Object #<Object> has no method 'call' Use --force to continue.

Aborted due to warnings.
```

Windows 7
grunt-cli v0.1.11
grunt v0.4.2
node v0.10.24
npm 1.3.21

Error print screen: http://prntscr.com/2luxoe

**Comment by bludrop** [comment]
`Cannot read property 'languages' of undefined` is discussed over here: https://github.com/helpers/handlebars-helper-compose/commit/c1a3187418963ec2d2d45239687e2b9d47f44157#commitcomment-5137128

The solution proposed there appears to work for now.

**Comment by diogomoretti** [comment]
Thanks for your reply!

But my `index.js`and `package.json` is already according to the link and still the same error :(

**Comment by diogomoretti** [comment]
Now its work for me.

Line 32 on _index.js_: `extras.init(customMarkedOpts);`

Ow, waiting for merge and npm registry :+1: 

cc @jonschlinkert

**Comment by doowb** [comment]
Published... Closing via #13

**Comment by diogomoretti** [comment]
Thanks :+1:

**Comment by jonschlinkert** [comment]
thanks! was about to look into this
