### ISSUE TITLE
Ordering, get date...

### ISSUE THREAD

**Issue by diogomoretti** [helpers/handlebars-helper-compose#14]
I need to sort my `{{compose}}` by date and get the year and month of the `date` on my .md files!

My compose:

```
{{#compose src="posts/*.md"}}
  <h1><a href="{{@basename}}">{{@title}}</a></h1>
  <p>{{{@content}}}</p>
{{/compose}}
```

My .md files:

```

---
title: Hello World
date: 2013-10-01

---

This is the {{title}} post...
```

I need the something like `{{@date.month}}` and the sort list of posts by date!

**Comment by jonschlinkert** [comment]
You should be able to do a custom `compare` function in the options: 

``` js
assemble: {
  site: {
    src: ['templates/*.hbs'],
    dest: 'foo/',
    options: {
      compose: {
        compare: function(a, b) {
          return a.data.date >= b.data.date ? 1 : -1;
        }
      }
    }
  }
}
```

You shouldn't need to add month if that's the format you're following, but let me know if you have any issues.

**Comment by diogomoretti** [comment]
How to use compare to `compose` loop?

**Comment by jonschlinkert** [comment]
? the compare function is running against the files globbed by the compose helper. 

See: 
- https://github.com/helpers/handlebars-helper-compose#compare
- https://github.com/helpers/handlebars-helper-compose/blob/master/Gruntfile.js#L206-L250
- and the "compare_*" test results in this directory: https://github.com/helpers/handlebars-helper-compose/tree/master/test/actual

**Comment by diogomoretti** [comment]
I'm using `{{@date}}` and return `Thu Oct 10 2013 21:00:00 GMT-0300 (BRT)`.

which variable i use to print only year?

**Comment by doowb** [comment]
This page might help ... https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date or you can checkout moment.js and see if you can use that.

**Comment by diogomoretti** [comment]
Resolved with `{{formatDate date "%Y"}}`.

Thanks!

**Comment by jonschlinkert** [comment]
Shouldn't you be able to do this:

``` js
assemble: {
  site: {
    src: ['templates/*.hbs'],
    dest: 'foo/',
    options: {
      compose: {
        compare: function(a, b) {
          a = a.data.date.getFullYear();
          b = b.data.date.getFullYear();
          return a >= b ? 1 : -1;
        }
      }
    }
  }
}
```

That should work with date. It's just a property on the context

**Comment by jonschlinkert** [comment]
:+1: great! glad you got it resolved

**Comment by diogomoretti** [comment]
Thanks for the alternative method!

**Comment by jonschlinkert** [comment]
they aren't alternative methods. with my method you can sort the order in which the files are globbed.  with the helper you can format the rendered date, but that doesn't change sorting order.

**Comment by jonschlinkert** [comment]
...you probably knew that, just wanted to clarify

**Comment by jonschlinkert** [comment]
lol @doowb I changed your link to mozilla's reference since the other site has a lot of misinformation on it. so you don't think you're going crazy
