### ISSUE TITLE
Did not know where else to post this...

### ISSUE THREAD

**Issue by akileez** [helpers/handlebars-helper-compose#2]
Any chance of reviving the old `{{partial}}` helper? I could never get it to work but I do have a potential use case for it using `{{compose}}`. I'll explain:

Presently, I use `{{compose}}` as a layout for specific partials instead of its original intended function. As an example, I create a panel "frame" partial with `{{compose}}` then use the `{{content}}` section to create unique content for the panel. This allows the panel frame to be reusable with alternating content. the YFM on the `{{content}}` file allows for customization on the fly. 

file: panel-block.hbs

```
{{#compose panel}}
{{#panel context}}
  {{#if heading}}
  {{#panel 'head'}}
    {{#if title}}
      {{h3 title class="panel-title"}}
    {{else}}
      {{head}}
    {{/if}}
  {{/panel}}
  {{/if}}
  {{{content}}}
  {{#if footer}}
  {{#panel 'foot'}}
    {{{footer}}}
  {{/panel}}
  {{/if}}
{{/panel}}
{{/compose}}
```

"content" file: panel-content01.hbs

``` html

---
context: "success"
heading: true
head: ""
title: "Testing out a new panel template"
footer: "The End"

---
<div class="panel-body">
  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rem, at, reiciendis debitis magni eaque numquam corporis excepturi labore itaque recusandae animi delectus ab ullam sunt in. Similique, et, maxime, dicta, vero sequi accusantium odio eum distinctio esse accusamus ipsum ipsa ducimus pariatur? Sunt odio vel nostrum praesentium maiores temporibus aperiam?
</div>
```

I then call this partial with `{{#parseJSON '{"panel": "panels/panel-content01.hbs"}'}} {{> panel-block }} {{/parseJSON}}`

It would be lovely to be able to do this instead:
`{{partial panel-block panel="panels/panel-content01.hbs"}}`

I currently use `{{compose}}` like this for modals, forms, tab content, and other misc things. It has become one of my goto helpers. 

So, what do you think? is it possible to bring this back or can this be achieve some other way? BTW, loving Assemble. Thanks a million for bringing this to life.

**Comment by jonschlinkert** [comment]
Awesome! glad you're getting use out of this. 

> instead of its original intended function

you're using it the way I was using it myself :-)  very cool. 

How about if we create a sandbox repo and you and I collaborate on getting these to work the way you need them to? I'd be happy to help.

**Comment by akileez** [comment]
Problem solved!!! 
I needed to use the `{{include}}` helper to achieve effect. 

```
{{include 'panel-block' panel="panels/panel-content01.hbs"}}
```

Took me some time to figure out the `{{include}}`. All examples show reading in a file from the root directory, i.e., 'README.md' or as a block helper. I did not know that you could use a partial enclosed in quotes without the path. Once I figured that out everything worked on my backup machine where I have Assemble 0.4.13 running. 

Now we both have an efficient way of calling these partials...
And thanks for the collaboration offer... next time... I sure there will be one. 

Remaining task left for me is to figure out why `{{compose}}` will not render content while `{{aggregate}}` and `{{post}}` will.

**Comment by jonschlinkert** [comment]
:+1: out of curiosity, which include helper did you use? I don't think I published on in the handlebars-helpers repo (?), but there are a few that I've used locally with other projects and/or helpers

**Comment by akileez** [comment]
Sorry about that... I had one lying in one of my helper files and forgot about. Here you go...

``` js
// {{include "template-partial" parentcontext=.. town=../town}}
    helpers.include = function(templatename, options) {

        var partial = Handlebars.partials[String(templatename)];
        if ( typeof partial === "string") {
            partial = Handlebars.compile(partial);
        }
        var context = _.extend({}, this, options.hash);
        return new Handlebars.SafeString(partial(context));
    };
```

I found this on the web about a month ago but never really used it. I was assuming that `{{include}}` was part of handlebars-helpers repo. I referenced usage examples from the boilerplate-markdown repo but never looked at the include helper there.

**Comment by jonschlinkert** [comment]
cool thanks, I guess I should split out one of the include helpers we've used into a new project, or just include it in the handlebars-helpers lib.

**Comment by jonschlinkert** [comment]
Also I just remembered that there is an include helped being used in the example-pagination repo in case that is useful
