### ISSUE TITLE
Unregister `helper-compose` from npm

### ISSUE THREAD

**Issue by thom4parisot** [helpers/handlebars-helper-compose#20]
It seems to be a ghost module, which git repo does not exist anymore.

https://www.npmjs.org/package/helper-compose targets https://github.com/assemble/helper-compose.

https://www.npmjs.org/package/handlebars-helper-compose seems to have superseded the former package.

**Comment by jonschlinkert** [comment]
thanks for the heads up here too, maybe instead of deleting the npm pkg I should re-add the git repo and just mark it as deprecated. I must have done that by accident - probably forgot that the former existed...

**Comment by jonschlinkert** [comment]
also, fwiw I'm using other helpers to solve the same or similar problems: https://github.com/assemble/assemble.io/blob/v0.3.0/structure/pages/helpers.hbs#L15-L25.

Here is the `inline` helper: https://github.com/assemble/assemble.io/blob/v0.3.0/structure/_helpers/inline.js#L32-L34

I highlighted those lines b/c they might seem strange, but what that does is allow me to aggregate a bunch of files and add some content before or after each file, like this "link to source" popover (which is created dynamically for every markdown file that gets inlined): 

![image](https://f.cloud.github.com/assets/383994/2378531/afad3d34-a88f-11e3-91d4-1641900c84a3.png)
