### ISSUE TITLE
Missing helper: 'compose'

### ISSUE THREAD

**Issue by regiskuckaertz** [helpers/handlebars-helper-compose#4]
Hello, I'm just starting out with Assemble and Grunt so please forgive me if this is not an issue. I keep getting the same error despite all my efforts and I'm kind of unable to get my head around it right now.

I have installed helper-compose and set up my assemble task as described in the Assemble doc. helper-compose is present in devDependencies as well. Then I wrote:

```
{{#compose 'src/pages/*.md'}}
  <h1>Title: {{title}}</h1>
  <p>{{{content}}}</p>
{{/compose}}
```

At compilation grunt chokes with Missing helper: 'compose'. I tried with {{compose}} instead of {{#compose}} but then there's a parse error on {{/compose}}:

Expecting 'EOF', 'CONTENT', 'COMMENT', 'OPEN_BLOCK', 'OPEN_INVERSE', 'OPEN', 'OPEN_UNESCAPED', 'OPEN_PARTIAL', got 'OPEN_ENDBLOCK' Use --force to continue.

Have you ever run into the same situation?

**Comment by doowb** [comment]
@regiskuckaertz there are 2 ways to register the helpers... did you try these...

``` javascript
assemble: {
  options: {
    helpers: ['helper-compose']
  }
}
```

Or add the `helper-compose` to the `keywords` in your `package.json` and it will be automatically loaded if it's in the `keywords` and `devDependencies`.

**Comment by regiskuckaertz** [comment]
Yeah! I added it to the keywords and now it works like a charm. Woaw, I would never have found this one. Thanks a lot @doowb

**Comment by doowb** [comment]
np, we're working on getting that added to the main documentation and to all the helpers.
