### ISSUE TITLE
README examples 404

### ISSUE THREAD

**Issue by tomByrer** [helpers/handlebars-helper-compose#6]
https://github.com/helpers/handlebars-helper-compose#example-templates-and-content
Tricky to deep-link source.  Might be better just to quote with `>` or ```, or to link to an actual webpage?

**Comment by jonschlinkert** [comment]
thanks for the heads up

**Comment by jonschlinkert** [comment]
fixed

**Comment by tomByrer** [comment]
README docs look nice, cheers!

**Comment by jonschlinkert** [comment]
Thanks!
